spring:
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
      hibernate.ddl-auto: create-drop
  sql:
    init.mode: always

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace # For DB analysis
